"""add price, category, seat, pinned

Revision ID: ef40403c2462
Revises: 7a2197129372
Create Date: 2026-07-17 12:49:42.558028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef40403c2462'
down_revision: Union[str, None] = '7a2197129372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('events', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('events', sa.Column('category', sa.String(length=50), server_default='General', nullable=False))
    # Hand-adjusted: tickets.seat is NOT NULL with no default, so existing rows
    # must be backfilled before the constraint is enforced. Seats are numbered
    # per event in ticket id order, matching the GA-001 scheme the service uses.
    op.add_column('tickets', sa.Column('seat', sa.String(length=20), nullable=True))
    op.execute(
        """
        UPDATE tickets AS t
        SET seat = 'GA-' || LPAD(numbered.row_number::text, 3, '0')
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY id) AS row_number
            FROM tickets
        ) AS numbered
        WHERE t.id = numbered.id
        """
    )
    op.alter_column('tickets', 'seat', nullable=False)
    op.create_unique_constraint('uq_tickets_event_seat', 'tickets', ['event_id', 'seat'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tickets_event_seat', 'tickets', type_='unique')
    op.drop_column('tickets', 'seat')
    op.drop_column('events', 'category')
    op.drop_column('events', 'price')
    op.drop_column('announcements', 'pinned')
    # ### end Alembic commands ###
